### ISSUE TITLE
RabbitMQ input plugin failures leave open sockets

### ISSUE THREAD

**Issue by asmaps** [logstash-plugins/logstash-input-rabbitmq#8] opened 2015-01-07 15:31 UTC
Although the issue in the JIRA tracker is quite old and the link in it doesn't even work anymore the problem seems to persist. I also get the error messages named in the ticket and I have tons of unclosed connections from the logstash server in my RabbitMQ which causes it to crash once a day...

https://logstash.jira.com/browse/LOGSTASH-1698

I hope that the issue gets a little attention if it is in the GitHub tracker :-)

**Comment by michaelklishin** [comment] 2015-01-07 16:04
The error you are linking to is a channel-level error. It should not result in a connection closure. See my reply in the JIRA issue, we can make the input re-connect but it may end up happening in a loop. So please investigate the root cause (why the exchange you want Logstash to use does not exist).

**Comment by michaelklishin** [comment] 2015-01-07 16:04
Also, the log message is wrong and misleading. This is NOT a connection error.

**Comment by SaucyWrong** [comment] 2015-03-23 17:40
I see this issue too when using this plugin on JRuby (this would be the march_hare implementation, I think).

The fact that the code treats this channel error as a connection issue when it isn't one is the heart of the issue.  The problem is that when the code retries it leaves the existing connection intact and creates a new one.  If subsequent queue binding operations fail these connections begin to pile up until either the RabbitMQ server crashes, or the JVM that logstash is running on runs out of memory and logstash terminates.  Even once the exchange is eventually created and the plugin can successfully bind a queue to it, these extra connections remain running until logstash is stopped.

Is it possible to reuse the existing connection and channel and attempt to rebind the queue after a certain amount of time, or to explicity close the channel and connection when retrying to prevent the unused connections from stacking up?

**Comment by andrewvc** [comment] 2015-08-25 21:38
I'm working on fixing this as we speak. It's already been fixed on the output and we're moving them to a common codebase.

**Comment by andrewvc** [comment] 2016-03-07 19:49
Fixed for a while. Reopen if you still have this!

**Closed by andrewvc** 2016-03-07 19:49 UTC
Labels: bug, needs details

**Comment by tsvenkat** [comment] 2016-04-26 20:36
Hi, what version of logstash includes this fix ?
I am running 1.5.3 and seeing this issue. What version should I move to ? (we are still using Elasticsearch 1.6.3).

Thanks,
Venkat
