### ISSUE TITLE
rabbitmq headers

### ISSUE THREAD

**Issue by fsarwari** [logstash-plugins/logstash-input-rabbitmq#19] opened 2015-03-01 01:18 UTC
Is it possible to read headers from the rabbitmq input plugin?

There's an old jira ticket it mentions such a feature. And from the ticket it looks like it should work. But I can't find anything in the docs to show how to extract headers from rabbitmq.

https://logstash.jira.com/browse/LOGSTASH-926

In the docs for an older version of logstash it has a headers_field as a config option. This option is no longer available in the newer versions.  

Also looked at "@metadata" and it seems to be empty.   

Thanks

**Comment by michaelklishin** [comment] 2015-03-01 09:23
Delivery info and properties are excluded from event decoding: https://github.com/logstash-plugins/logstash-input-rabbitmq/blob/master/lib/logstash/inputs/rabbitmq/bunny.rb#L108-112.

Not sure if Logstash core allows events to have metadata these days.

**Comment by fsarwari** [comment] 2015-03-05 21:16
michaelklishin, thanks for the explanation.  The metadata wouldn't really have to pass to logstash core.  It could be copied to a field within in the input plugin and that way it could get passed to the filter. (not sure if add_field works that way).
But according to the source mentioned above (bunny.rb) it looks like everything except for data is discarded.  Probably for performance reasons.

thanks again.

**Comment by michaelklishin** [comment] 2015-03-05 21:22
@fsarwari not for performance reasons. Nobody thought it would be particularly useful when the plugin was re-written about a year ago. We can add it. The question is, is there required infrastructure for this change in the plugin system these days, and how many people want this.

**Comment by magnusbaeck** [comment] 2015-03-17 23:23
This is a duplicate of #7 which I'm working on addressing since I'm very interested in getting the routing key and timestamp from the consumed messages. I'll close that issue in favor of this one.

**Comment by electrical** [comment] 2015-03-17 23:48
@michaelklishin nowadays ( LS 1.5 ) we have a @metadata object that can contain information but won't be indexed.
Perhaps that can used. See https://github.com/elastic/logstash/pull/1836 for some details.

**Comment by Semyazz** [comment] 2015-07-15 10:58
what should be in that **metadata** object? I passed some **properties** to the queue, but I see no way to retrieve them in Logstash. I can't find both: headers and properties in metadata field. It's just empty. I'm particularly interested in **user_id** property. I can send data to RMQ with property user-id which will be validated against client's certificate CommonName so nobody can spoof the message, but I'd like also to pass that msg to logstash so I can use it in filters and output...

**Comment by magnusbaeck** [comment] 2015-07-15 11:05
Yes, that's exactly the kind of scenario that solving this issue will address (do note that the issue is still open). I'm done with the implementation but got stalled when I reached the unit tests. I might have time to revisit this in the upcoming couple of weeks.

**Comment by Ruben-E** [comment] 2015-08-14 05:30
Any updates about this?

**Comment by magnusbaeck** [comment] 2015-08-14 05:44
I haven't been able to prioritize the completion of this. The fact that the Logstash team doesn't seem to be reviewing and merging even trivial typo-correction pull requests isn't really motivating me to complete the rspec work. I can upload what I've got so far though.

**Comment by jingzhaoou** [comment] 2015-09-13 19:39
In my project, I am pulling RabbitMQ messages into Elasticsearch using this plugin. Routing keys are required so that I know where the messages come from. I am willing to contribute to this if someone can help me get stared.

**Comment by cian** [comment] 2015-09-17 01:14
@jingzhaoou If you could test my patch and see if it gives you want you need I would be grateful to hear your feedback [@metadata][routingKey] should contain what you need.

**Comment by asbjornu** [comment] 2015-12-16 15:10
I'd love to have this available as well. Especially exchange, queue name and routing key would be useful, but everything we can get out of RabbitMQ should be made available in `@metadata`, imho.

**Comment by andrewvc** [comment] 2016-03-07 19:52
This has just been merged into master and should be released soon!

**Closed by andrewvc** 2016-03-07 19:52 UTC
