### ISSUE TITLE
No error if RabbitMQ goes down

### ISSUE THREAD

**Issue by ebuildy** [logstash-plugins/logstash-input-rabbitmq#76] opened 2016-03-29 17:39 UTC
Before version 3.3.0, when Rabbit server went down, logstash throws:

```
Queue subscription ended! Will retry in 5s
RabbitMQ connection down, will wait to retry subscription
```

With version 4.0.1, nothing happen (as you can on docker-compose logs, here https://gist.github.com/ebuildy/d405dab7dbaca2e3a03dc2a7fa6f5b29) if queue server is down, is it normal?

Thanks you,

**Comment by andrewvc** [comment] 2016-03-30 14:10
@ebuildy that is because we now use the RabbitMQ library's built in auto-reconnect facility which is more robust. We'd be glad to accept a patch that hooks into it and logs these events however!

**Comment by ebuildy** [comment] 2016-03-30 14:19
You are talking about this: https://www.rabbitmq.com/api-guide.html#recovery ?

Thanks you, I mush finished some PR on other logstash plugins and RabbitMQ Java client (https://github.com/rabbitmq/rabbitmq-java-client/issues/138) before, then I will give an eye to it.

**Comment by digitalkaoz** [comment] 2016-10-18 15:32
@andrewvc beside there are no logs if the rabbitmq server closes the channel, a reconnect isnt happening, why i assume logstash with rabbitmq input is not usable atm, especially in a dockerized environment... any solutions here? we to use a haproxy in between rabbit and logstash

**Comment by andrewvc** [comment] 2016-10-18 16:48
@digitalkaoz why is the rabbitmq server closing the channel? 

AFAIK if you do that the meaning is you want the client to stop and not restart. Please correct me if I'm wrong here.

**Comment by andrewvc** [comment] 2016-10-18 16:49
@digitalkaoz that's a different situation, may I add, from one where the server has gone down as a result of an error.

**Comment by andrewvc** [comment] 2016-10-18 16:51
@ebuildy @digitalkaoz , if you all can share a reproducible test case I'd be glad to try it and find a fix. Just list the steps to reproduce, preferably just using logstash and a local rabbitmq.

**Comment by digitalkaoz** [comment] 2016-10-18 18:05
@andrewvc the rabbit an haproxy server are restarted during deployments (they are just docker containers)

here the setup:

rabbitmq -> 5672(tcp) -> haproxy -> 5672(tcp) -> logstash

`rabbitmq.conf` is default

`haproxy.conf`
```
listen amqp
        mode tcp
        option tcplog
        bind *:5672
        log global
        balance         roundrobin
        timeout connect 2s
        timeout client  2m
        timeout server  2m
        option          clitcpka
        option tcp-check
        server rabbitmq:5672 check port 5672
```

`logstash.conf`

```ruby
input {
    rabbitmq {
        connection_timeout => 1000
        heartbeat => 30
        host => "haproxy"
        subscription_retry_interval_seconds => 30
        queue => "logs"
        user => "guest"
        password => "guest"
    }
```

if we only restart rabbitmq it seems fine when we gracefully shutdown the server:

```bash
$ docker exec rabbitmq rabbitmqctl close_connection {$CON_ID} "rabbit shutdown"
$ docker exec rabbitmq rabbitmqctl stop_app
```

we explicitly close the connection the force the logstash-rabbitmq-input plugin to force a plugin restart

but if we restart haproxy the tcp gets cut off ungracefully and the logstash plugin wont notice the channel is closed (and doenst go into restart mode) because it received an error frame. the java recovery stuff doesnt seem to work for that.

hope thats enough information

**Comment by digitalkaoz** [comment] 2016-10-18 18:06
i think thats a quite common scenario in a containerized world

**Comment by digitalkaoz** [comment] 2016-10-18 20:38
when i restart logstash i get the following error: ```An unexpected error occurred!", :error=>com.rabbitmq.client.AlreadyClosedException: connection is already closed due to connection error; cause: java.io.EOFException, :class=>"Java::ComRabbitmqClient::AlreadyClosedException", :backtrace=>["com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(com/rabbitmq/client/impl/AMQChannel.java:195)", "com.rabbitmq.client.impl.AMQChannel.rpc(com/rabbitmq/client/impl/AMQChannel.java:241)", "com.rabbitmq.client.impl.ChannelN.basicCancel(com/rabbitmq/client/impl/ChannelN.java:1127)", "java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)", "RUBY.method_missing(/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.15.0-java/lib/march_hare/channel.rb:874)", "RUBY.shutdown_consumer(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-rabbitmq-4.1.0/lib/logstash/inputs/rabbitmq.rb:279)", "RUBY.stop(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-rabbitmq-4.1.0/lib/logstash/inputs/rabbitmq.rb:273)", "RUBY.do_stop(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/inputs/base.rb:83)", "org.jruby.RubyArray.each(org/jruby/RubyArray.java:1613)", "RUBY.shutdown(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:385)", "RUBY.stop_pipeline(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/agent.rb:413)", "RUBY.shutdown_pipelines(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/agent.rb:406)", "org.jruby.RubyHash.each(org/jruby/RubyHash.java:1342)", "RUBY.shutdown_pipelines(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/agent.rb:406)", "RUBY.shutdown(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/agent.rb:402)", "RUBY.execute(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/agent.rb:233)", "RUBY.run(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/runner.rb:94)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:281)", "RUBY.run(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/runner.rb:99)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:281)", "RUBY.initialize(/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/task.rb:24)", "java.lang.Thread.run(java/lang/Thread.java:745)"], :level=>:warn}```

**Comment by andrewvc** [comment] 2016-10-18 23:31
@digitalkaoz thanks for the very detailed description here! 

@michaelklishin should the java client's auto connection recovery just handle this?

**Comment by michaelklishin** [comment] 2016-10-19 04:37
It [takes time to detect peer unavailability](http://www.rabbitmq.com/heartbeats.html). I don't see how this is a connection recovery issue: recovery cannot start if a client connection is still considered to be alive.

**Comment by michaelklishin** [comment] 2016-10-19 04:37
Also: do not set heartbeats to a value lower than 5 seconds. That is recipe for false positives.

**Comment by digitalkaoz** [comment] 2016-10-19 05:42
We waited alot but logstash wont recover the Connection. I would rather get
false positives than nothing...any more ideas? The Error Message at the End
says it very clear. The Channel was already closed, bc it received an Error
Frame. The Connection seemed to get Alive again within the time Span. But
the Channel is unusable

Michael Klishin <notifications@github.com> schrieb am Mi., 19. Okt. 2016,
06:37:

**Comment by andrewvc** [comment] 2016-10-19 12:52
@michaelklishin thanks for popping in! 

He's setting the heartbeat to 30 seconds. It's confusing because the connection timeout is in millis, but the heartbeat is in seconds. 

I think this is correct yes? Looking at the source of the java client it looks like timeout is set in millis and heartbeats in seconds. Is that all correct?

**Comment by digitalkaoz** [comment] 2016-10-25 10:40
@andrewvc @michaelklishin i created a tiny docker-compose setup to reproduce this issue:

https://github.com/digitalkaoz/rabbit-haproxy-logstash-fail

simply follow the `reproduce` steps...

**Comment by michaelklishin** [comment] 2016-10-25 11:04
Heartbeat timeout is in seconds per protocol spec. Also see [this thread](https://groups.google.com/d/msg/rabbitmq-users/qOjN8-U5oYI/o-2g0o7mAgAJ).

**Comment by michaelklishin** [comment] 2016-10-25 11:10
So you have HAproxy in between. HAproxy has its own timeouts (which heartbeats in theory make irrelevant but still) and what RabbitMQ sees is a TCP connection from HAproxy, not the client. I can do a March Hare release with a preview version of the 3.6.6 Java client, however.

**Comment by andrewvc** [comment] 2016-10-25 13:09
Thanks @digitalkaoz , I'll try and repro today.

**Comment by andrewvc** [comment] 2016-10-25 13:10
Also thanks for the background @michaelklishin . I'm wondering if what's happening is that HAProxy is switching the backend without letting logstash know, and without disconnecting from logstash. Will report back.

**Comment by digitalkaoz** [comment] 2016-10-25 13:10
it still fails when i wait lets say 5 minutes... @michaelklishin as i understand the relevant fix is in https://github.com/rabbitmq/rabbitmq-java-client/releases/tag/v4.0.0.M2 ?

**Comment by michaelklishin** [comment] 2016-10-25 13:11
@andrewvc typically proxies propagate upstream connection loss. At least that's what HAproxy does by default. In fact, if it didn't then the two logical ends of the TCP connection would be out of sync.

I doubt it's a Java client problem here but I've [updated March Hare to the latest 3.6.x version from source](https://github.com/ruby-amqp/march_hare/commit/4c8da4a94ed39606b120b00174b26a2b9c07d509).

**Comment by michaelklishin** [comment] 2016-10-25 13:13
@digitalkaoz I'm sorry but there is no evidence that I have seen that this is a client library issue. A good thing to try would be to eliminate HAproxy from the picture entirely and also verify the effective heartbeat timeout value (management UI displays it on the connection page).

**Comment by digitalkaoz** [comment] 2016-10-25 13:20
sure if i remove haproxy from the setup the reconnect works. but thats not a typical setup (or at least at scale)

with haproxy in the middle, reconnect fails (even with a heartbeat of `10s`)

**Comment by michaelklishin** [comment] 2016-10-25 13:27
It should. We don't know why that doesn't happen: that's why I recommended checking the actual effective value.

**Comment by digitalkaoz** [comment] 2016-10-25 13:33
after restarting rabbit there is no connection alive on the rabbit-node because nobody initiated a new connection. neither haproxy, nor logstash. bc. their connection is still there but defacto useless?

**Comment by andrewvc** [comment] 2016-10-25 14:02
@michaelklishin, is there a best practice here for accomplishing what @digitalkaoz wants to accomplish? I think having a layer of indirection via a load balancer makes sense. This is something that's come up multiple times, I'm wondering if the RabbitMQ project has an official stance here.

**Comment by michaelklishin** [comment] 2016-10-25 14:10
There's no stance as HAproxy is supposed to be transparent to the client.

@digitalkaoz HAproxy is not supposed to initiate any connections upstream unless a new client connects to it.

Can we please stop guessing and move on to forming hypotheses and verifying them? The first one I have is: the heartbeat value is actually not set to what the reporter thinks it is used. I've mentioned how this can be verified above. Without this we can pour hours and hours of time and get nothing out of it. My team already spends hours every day on various support questions and we would appreciate if the reporters cooperated a bit to save us all some time.

I also pushed a Java client update to March Hare, even though I doubt it will change anything.

A [Wireshark/tcpdump](https://www.rabbitmq.com/amqp-wireshark.html) capture will provide a lot of information to look at.

**Comment by michaelklishin** [comment] 2016-10-25 14:12
A Wireshark capture should make it easy to see heartbeat frames on the wire: not only their actual presence but also timestamps (they are sent at roughly 1/2 of the effective timeout value).

**Comment by digitalkaoz** [comment] 2016-10-25 14:20
@michaelklishin the heartbeat is set to `10s` as i told you above...but that didnt change anything, or do you mean some other value?

![screen shot 2016-10-25 at 16 17 12](https://cloud.githubusercontent.com/assets/293591/19689702/88693d20-9ace-11e6-8423-0355f07e6384.png)

**Comment by michaelklishin** [comment] 2016-10-25 14:21
What is in server logs? HAproxy logs?

**Comment by digitalkaoz** [comment] 2016-10-25 14:34
mh the haproxy logs are not very helpful:

```
proxy_1     | 00000000:amqp.srvcls[0007:0008]
proxy_1     | 00000000:amqp.clicls[0007:0008]
proxy_1     | 00000000:amqp.closed[0007:0008]
rabbit_1 exited with code 137
proxy_1     | 00000001:amqp.accept(0006)=0008 from [172.18.0.5:49608]
proxy_1     | [WARNING] 298/143248 (1) : Server amqp/rabbit is DOWN, reason: Layer4 timeout, check duration: 5001ms. 0 active and 0 backup servers left. 1 sessions active, 0 requeued, 0 remaining in queue.
proxy_1     | [ALERT] 298/143248 (1) : proxy 'amqp' has no server available!
```

**Comment by michaelklishin** [comment] 2016-10-25 14:39
@digitalkaoz can you please post a less abridged log together with RabbitMQ node and Logstash logs?

**Comment by michaelklishin** [comment] 2016-10-25 14:40
According to the abridged log above, HAproxy does accept a client connection, then detects that an upstream node is down and there are no more upstreams to try. Then… we don't know what happens because the log ends.

**Comment by digitalkaoz** [comment] 2016-10-25 14:41
there are no more logs from any of the systems (neither haproxy, nor logstash)

**Comment by michaelklishin** [comment] 2016-10-25 14:44
@digitalkaoz what about RabbitMQ? Can you take a tcpdump or Wireshark capture?

**Comment by digitalkaoz** [comment] 2016-10-25 14:52
can i recommend cloning the repo? im not very familiar with tcp connection debugging :/

**Comment by digitalkaoz** [comment] 2016-10-25 14:56
@michaelklishin i attached the full log here https://gist.github.com/digitalkaoz/8f1825dd1ad2976a1516afdccf120e7f

**Comment by michaelklishin** [comment] 2016-10-25 15:06
From RabbitMQ log, after a few inbound connections and restarts:

```
rabbit_1    | accepting AMQP connection <0.400.0> (172.18.0.3:38102 -> 172.18.0.2:5672)
rabbit_1    |
rabbit_1    | =WARNING REPORT==== 25-Oct-2016::14:49:07 ===
rabbit_1    | closing AMQP connection <0.400.0> (172.18.0.3:38102 -> 172.18.0.2:5672):
rabbit_1    | client unexpectedly closed TCP connection
```

This means that at `25-Oct-2016::14:49:07` RabbitMQ did register an inbound AMQP 0-9-1 client connection and then its TCP connection was immediately closed by HAproxy.

I am not sure what exactly `srvcls` and `clicls` are, probably "server connection closed" and "client connection closed", respectively:

```
proxy_1     | 00000001:amqp.srvcls[0008:0007]
proxy_1     | 00000001:amqp.clicls[0008:0007]
proxy_1     | 00000001:amqp.closed[0008:0007]
```

I'm not sure why it happens, perhaps HAproxy decides to reset all connections now that it has an upstream to connect to. Also this should not prevent March Hare from attempting to connect again after a period of time.

Can you try March Hare master?

**Comment by digitalkaoz** [comment] 2016-10-25 15:09
following this guide? or is there some easier way? https://github.com/logstash-plugins/logstash-input-rabbitmq#22-run-in-an-installed-logstash

**Comment by digitalkaoz** [comment] 2016-10-25 15:11
maybe we also need some haproxy ninja? everything i try is an educated guess how to configure all of those 5000 different options in my tcp-proxy. do you know any?

**Comment by andrewvc** [comment] 2016-10-25 16:48
Here's one interesting datapoint, if I kill haproxy and start it back up (using your very useful docker-compose @digitalkaoz ) everything works great. So it's something in the haproxy config I think.

**Comment by andrewvc** [comment] 2016-10-25 18:03
OK, well, this is definitely something between the Java client and HAProxy. Here's a [pcap dump](https://drive.google.com/open?id=0B8_TFagdGjS4SXlwZjB2LVlETGs) using the docker compose stuff from the haproxy node.

The sequence of events was:

1. Everything running correctly
2. RMQ killed
3. RMQ brought back up
4. Logstash restarted
5. Producer Restarted

I'm too busy to keep digging on this till next week. Maybe someone else could find something here.

Fun fact, if I kill and restart haproxy everything recovers correctly. It's something about the way connections are re-initiated through haproxy that is funky.

**Comment by digitalkaoz** [comment] 2016-10-25 18:31
But neverless, the logstash plugin should recognize the closed Channel and
start the recovery process.

Andrew Cholakian <notifications@github.com> schrieb am Di., 25. Okt. 2016,
18:48:

**Comment by andrewvc** [comment] 2016-10-25 18:37
@digitalkaoz that's the tricky thing. The java library is supposed to do this! According to http://rubymarchhare.info/articles/error_handling.html March Hare should handle that itself. That makes it a library client bug. Please correct me if I'm wrong @michaelklishin

**Comment by andrewvc** [comment] 2016-10-25 18:38
I agree that we should make this work in Logstash BTW, if the client cannot be fixed then we'll have to find a workaround, but I'd prefer to see if we can fix the client first.

**Comment by andrewvc** [comment] 2016-10-25 18:41
I think the key issue here is RMQ server identity. If I stop and start the proxy it's fine. If I start and stop the proxy AND the rabbitmq server it is not. @michaelklishin could the issue be that the recovery code assumes the consumer will be bound to the same server? 

That is to say, the automatic recovery assumes that the other end would be the same rabbitmq instance that was there before, but swapping instances out is not supported?

**Comment by michaelklishin** [comment] 2016-10-25 19:34
As soon as there's evidence (and not guesses) that there's a March Hare or Java client bug, I'd be happy to look into it. So far I see no solid evidence.  I have provided enough pointers, hypotheses and general investigation directions. My recommendations are being largely ignored (it takes several requests to get data, no traffic captures provided, March Hare master wasn't tried).

**Comment by michaelklishin** [comment] 2016-10-25 19:35
@andrewvc clients have no way of identifying what RabbitMQ server they are connected to. It would be pretty silly to only allow recovery to re-connect to the same node because in practice reconnection to the same node will not succeed.

**Comment by michaelklishin** [comment] 2016-10-25 19:51
So I have conducted a little experiment with March Hare master, vanilla RabbitMQ 3.6.5 with all defaults, and HAproxy 1.5 (not sure what the exact version is, possibly even a `-dev` version) with
the following config:

```
global
        log 127.0.0.1   local0
        log 127.0.0.1   local1 notice
        maxconn 4096
        user antares
        group staff
        # daemon
        debug

defaults
        log        global
        option     dontlognull
        option     redispatch
        retries    3
        maxconn    2000
        contimeout 5000
        clitimeout 50000
        srvtimeout 50000

backend rabbitmq
        mode         tcp
        server node1 127.0.0.1:5672 maxconn 2048

frontend rabbitmq-in
        bind *:5673
        balance
        default_backend rabbitmq
```

My March Hare connection code is about as trivial as it gets:

``` ruby
c = MarchHare.connect(port: 5673, requested_heartbeat: 8)
```

and then I periodically check if the connection is open:

``` ruby
c.open? # => true
```

I then shut down RabbitMQ a few times, observe that the connection is closed, start it back, observe that it is open again in a few seconds. This repeatedly worked 5 times in a row.

Here's HAproxy log, you can see inbound connections from different ephemeral ports (read: different client sockets):

```
00000001:rabbitmq-in.accept(0004)=0005 from [127.0.0.1:53004]
00000001:rabbitmq.srvcls[0005:0006]
00000001:rabbitmq.clicls[0005:0006]
00000001:rabbitmq.closed[0005:0006]
00000002:rabbitmq-in.accept(0004)=0005 from [127.0.0.1:53023]
00000002:rabbitmq.clicls[0005:0006]
00000003:rabbitmq-in.accept(0004)=0005 from [127.0.0.1:53033]
00000003:rabbitmq.srvcls[0005:0007]
00000003:rabbitmq.clicls[0005:0007]
00000003:rabbitmq.closed[0005:0007]
00000004:rabbitmq-in.accept(0004)=0005 from [127.0.0.1:53038]
00000004:rabbitmq.srvcls[0005:0007]
00000004:rabbitmq.clicls[0005:0007]
00000004:rabbitmq.closed[0005:0007]
00000005:rabbitmq-in.accept(0004)=0005 from [127.0.0.1:53054]
00000005:rabbitmq.srvcls[0005:0007]
00000005:rabbitmq.clicls[0005:0007]
00000005:rabbitmq.closed[0005:0007]
00000006:rabbitmq-in.accept(0004)=0005 from [127.0.0.1:53060]
00000006:rabbitmq.clicls[0005:0007]
00000007:rabbitmq-in.accept(0004)=0005 from [127.0.0.1:53067]
```

Here's RabbitMQ log from the most recent restart:

```
=INFO REPORT==== 25-Oct-2016::22:45:03 ===
Stopped RabbitMQ application

=INFO REPORT==== 25-Oct-2016::22:45:03 ===
Halting Erlang VM

=INFO REPORT==== 25-Oct-2016::22:45:13 ===
Starting RabbitMQ 3.6.5 on Erlang 19.1
Copyright (C) 2007-2016 Pivotal Software, Inc.
Licensed under the MPL.  See http://www.rabbitmq.com/

…

=INFO REPORT==== 25-Oct-2016::22:45:15 ===
Memory limit set to 5381MB of 5978MB total.

=INFO REPORT==== 25-Oct-2016::22:45:15 ===
Disk free limit set to 6269MB

=INFO REPORT==== 25-Oct-2016::22:45:15 ===
Limiting to approx 499900 file handles (449908 sockets)

=INFO REPORT==== 25-Oct-2016::22:45:15 ===
FHC read buffering:  OFF
FHC write buffering: ON

=INFO REPORT==== 25-Oct-2016::22:45:15 ===
Priority queues enabled, real BQ is rabbit_variable_queue

=INFO REPORT==== 25-Oct-2016::22:45:15 ===
Management plugin: using rates mode 'basic'

=INFO REPORT==== 25-Oct-2016::22:45:15 ===
msg_store_transient: using rabbit_msg_store_ets_index to provide index

=INFO REPORT==== 25-Oct-2016::22:45:15 ===
msg_store_persistent: using rabbit_msg_store_ets_index to provide index

=INFO REPORT==== 25-Oct-2016::22:45:15 ===
started TCP Listener on [::]:5672

=INFO REPORT==== 25-Oct-2016::22:45:15 ===
started SSL Listener on [::]:5671

=INFO REPORT==== 25-Oct-2016::22:45:15 ===
rabbit_stomp: default user 'guest' enabled

=INFO REPORT==== 25-Oct-2016::22:45:15 ===
started STOMP TCP Listener on [::]:61613

=INFO REPORT==== 25-Oct-2016::22:45:15 ===
MQTT retained message store: rabbit_mqtt_retained_msg_store_dets

=INFO REPORT==== 25-Oct-2016::22:45:15 ===
started MQTT TCP Listener on [::]:1883

=INFO REPORT==== 25-Oct-2016::22:45:15 ===
opening log file: "/tmp/rabbit-mgmt/access.log.2016_10_25_19"

=INFO REPORT==== 25-Oct-2016::22:45:15 ===
Management plugin started. Port: 15672

=INFO REPORT==== 25-Oct-2016::22:45:15 ===
Statistics event collector started.

=INFO REPORT==== 25-Oct-2016::22:45:15 ===
Statistics channel stats collector started.

=INFO REPORT==== 25-Oct-2016::22:45:15 ===
Statistics queue stats collector started.

=INFO REPORT==== 25-Oct-2016::22:45:15 ===
Statistics database started.

=INFO REPORT==== 25-Oct-2016::22:45:15 ===
Statistics garbage collector started for table aggr_queue_stats_fine_stats with interval 5000.

…

=INFO REPORT==== 25-Oct-2016::22:45:15 ===
Statistics garbage collector started for table aggr_exchange_stats_fine_stats with interval 5000.

=INFO REPORT==== 25-Oct-2016::22:45:15 ===
Server startup complete; 12 plugins started.
 * rabbitmq_shovel_management
 * rabbitmq_management
 * rabbitmq_web_dispatch
 * webmachine
 * rabbitmq_jms_topic_exchange
 * rabbitmq_consistent_hash_exchange
 * rabbitmq_shovel
 * rabbitmq_management_agent
 * rabbitmq_mqtt
 * rabbitmq_stomp
 * mochiweb
 * amqp_client

=INFO REPORT==== 25-Oct-2016::22:45:15 ===
Statistics garbage collector started for table aggr_node_stats_coarse_node_stats with interval 5000.

…

=INFO REPORT==== 25-Oct-2016::22:45:15 ===
Statistics garbage collector started for table connection_stats with interval 5000.

=INFO REPORT==== 25-Oct-2016::22:45:19 ===
accepting AMQP connection <0.629.0> (127.0.0.1:53068 -> 127.0.0.1:5672)
```

As you can see, the most recent HAproxy connection is on port `53067` and RabbitMQ accepts a connection from `53068` (HAproxy), which means the two descriptors were opened in rapid succession. So yes, this is real: March Hare recovers successfully when an HAproxy upstream goes down.

**Comment by michaelklishin** [comment] 2016-10-25 20:09
In the provided TCP dump file, if we apply a display filter that only displays the packets/segments/frames sent by the Logstash process (which seems to be on host `172.19.0.5`, according to my understanding of the heartbeat frame exchange) like this:

```
ip.src eq 172.19.0.5
```

we see that it attempts to connect and gets an `RST` (reset) packet:

```
173	2016-10-25 17:19:06.146341	172.19.0.5	59566	172.19.0.4	5672	TCP	54	59566 → 5672 [RST] Seq=10 Win=0 Len=0
```

and then the next time it tries and succeeds is over a minute later:

```
236	2016-10-25 17:20:26.381197	172.19.0.5	59812	172.19.0.4	5672	TCP	66	59812 → 5672 [ACK] Seq=9 Ack=494 Win=30336 Len=0 TSval=362368 TSecr=362368
```

so depending on the recovery interval used, this may or may not indicate that the client did not try to reconnect more than once. Default interval is 5 seconds.

**Comment by digitalkaoz** [comment] 2016-10-25 20:38
@michaelklishin thanks that you dig into. im trying to help all i can, but im neither into java-rabbitmq-client nor march-here nor logstash-plugins. 

can you open a channel too (not just a connection, because thats what the logstash-plugin does, which gets closed unnoticed)

**Comment by michaelklishin** [comment] 2016-10-25 21:08
```
jruby-9.1.2.0 :003 > [c.open?, ch.open?]
 => [true, true]
# stop RabbitMQ
jruby-9.1.2.0 :004 > [c.open?, ch.open?]
 => [false, false]
jruby-9.1.2.0 :005 > [c.open?, ch.open?]
 => [false, false]
# start RabbitMQ
jruby-9.1.2.0 :006 > [c.open?, ch.open?]
 => [false, false]
# node finishes booting
jruby-9.1.2.0 :007 > [c.open?, ch.open?]
 => [true, true]
```

**Comment by michaelklishin** [comment] 2016-10-25 21:58
March Hare `2.19.0` is out.

**Comment by andrewvc** [comment] 2016-10-25 22:09
Great, Il'l try upgrading tomorrow. With 2.18.0 I was seeing a state where the connection was closed but auto-recovery wasn't touching it. I'll have more tmrw.

**Comment by andrewvc** [comment] 2016-10-26 01:22
Bumping versions fixed this issue to me @michaelklishin . Thanks for pushing the new version.

Opened this PR to bump it https://github.com/logstash-plugins/logstash-mixin-rabbitmq_connection/pull/32

We need a separate PR to do a better job logging bad connections.

**Comment by andrewvc** [comment] 2016-10-26 01:49
Please respond to this ticket if you're still experiencing this bug @digitalkaoz and we can reopen it . You should be able to upgrade by running `logstash-plugin --update`

**Comment by digitalkaoz** [comment] 2016-10-26 19:21
@andrewvc im not sure how it fixes it for you?

`march_hare-2.19.0`  
`logstash-mixin-rabbitmq_connection-4.2.0` 
`logstash-input-rabbitmq-4.1.0` 

same thing, if i kill and start rabbit logstash still doesnt recover the connection, last message from logstash was now (thanks to your newest commit ;) ) 

`{:timestamp=>"2016-10-26T19:12:31.687000+0000", :message=>"RabbitMQ connection was closed!", :url=>"amqp://guest:XXXXXX@proxy:5672/", :automatic_recovery=>true, :cause=>com.rabbitmq.client.ShutdownSignalException: connection error, :level=>:warn}` 

the important thing is to not restart logstash!
can you tell me your step how it worked on your side?

**Comment by andrewvc** [comment] 2016-10-26 22:32
@digitalkaoz yes, I followed the following your procedure (using your excellent docker-compose):

1. Start up the hole stack, wait for LS to come up
2. docker-compose kill rabbit producer
3. docker-compose up rabbit producer

That all works for me. Not for you? BTW, I'd recommend upgrading to logstash-input-rabbitmq 5.2.0

**Comment by digitalkaoz** [comment] 2016-10-27 07:25
still no luck:

```
logstash:5
logstash-mixin-rabbitmq_connection-4.2.0
logstash-input-rabbitmq-5.2.0
march_hare-2.19.0
```

what am i doing wrong?

my steps:

```
$ docker-composer up #all up
$ docker-compose kill rabbit producer #kill rabbit+producer
$ docker-compose start rabbit producer #restart rabbit+producer
```

still logstash wont catch up :/

**Comment by michaelklishin** [comment] 2016-10-27 08:10
@digitalkaoz I'm sorry to be so blunt but if you want to get to the bottom of it you need to put in some debugging effort of your own. We have provided several hypotheses, investigated at least two, explained what various log entries mean, what can be altered to identify what application may be introducing the behaviour observed, analyzed at least one Wireshark dump, and based on all the findings produced a new March Hare version. That's enough information to understand how to debug a small distributed system like this one.

Asking "what am I doing wrong" is unlikely to be productive. Trying things at random is unlikely to be efficient.

**Comment by andrewvc** [comment] 2016-10-28 13:12
@digitalkaoz can you update the docker-compose stuff with the latest? One thing that was different in my repro is that I ran everything except logstash in docker. That shouldn't make a difference, but maybe it does.

**Comment by andrewvc** [comment] 2016-10-31 21:56
Hey @digitalkaoz I'm still glad to help you get to the bottom of this. @michaelklishin thanks so much for your help, I really appreciate it! 

I'm glad to personally put in some more hours here myself. What would help me move this forward @digitalkaoz is if you could update your docker config to the latest versions so we can be reproing the same things.

**Comment by digitalkaoz** [comment] 2016-11-01 07:55
sorry @andrewvc i had an busy weekend.

i updated everything to the latests version, but still no luck. the repo is up to date now.

```
$ docker-composer up #all up
$ docker-compose kill rabbit producer
$ sleep 10
$ docker-compose start rabbit producer
```

**Comment by michaelklishin** [comment] 2016-11-01 08:01
In the snippet above both RabbitMQ and publisher are shut down and started at the same time. Note that this is not the same steps that at least some in this thread performed and creates a natural race condition between the two starting. If the producer starts before RabbitMQ then *connection recovery WILL NOT BE ENGAGED* since there never was a successful connection to recover: initial TCP connection will fail.

**Comment by digitalkaoz** [comment] 2016-11-01 09:18
@michaelklishin the producer waits 10s before doing anything, so rabbit has time to start

**Comment by andrewvc** [comment] 2016-11-01 21:53
I've reopened this issue now that I've reconfirmed it @digitalkaoz , but as I've traced the issue to what I believe to definitely be a MarchHare bug we should move the discussion to https://github.com/ruby-amqp/march_hare/issues/107

Interestingly MarchHare *does* recover if rabbitmq comes back in under the 5s window. If it takes any longer it is perma-wedged.

**Comment by andrewvc** [comment] 2016-11-01 21:53
BTW, thanks for the excellent docker compose @digitalkaoz

**Comment by jordansissel** [comment] 2016-11-01 22:47
@andrewvc and I worked on this for a while today. Packet capture in wireshark showed indeed that the rabbitmq client from Logstash was waiting 5 seconds (as expected) when rabbitmq was stopped before reconnecting. However, that reconnect attempt went like this:

* TCP handshake with Haproxy ✅ 
* Client (logstash) sends what looks like a hello or protocol initialization: `AMQP\0\0\9\1` ("AMQP" + hex 00000901) ✅ 
* 5 seconds later, Client starts tcp teardown, sending FIN to close the connection. Presumably because the backend (haproxy) did not respond ✅ 
* No further connection attempts are made by the client.  ❌ 

The problem we are looking at now is to try and understand why the rabbitmq client is not reconnecting after the first reconnection attempt had timed out.

**Comment by jordansissel** [comment] 2016-11-01 23:12
Based on the behavior, I was able to reproduce this without docker.

* Run rabbitmq + logstash
* Let logstash rmq input connect
* Stop rabbitmq
* run `nc -l 5672` to accept the next connection retry from Logstash
* After this attempt to reconnect, rmq input never tries again.

**Comment by michaelklishin** [comment] 2016-11-01 23:33
@jordansissel this is an edge case in the protocol. Before connection negotiation happens we cannot set up a heartbeat timer but without it it takes a long time to detect unresponsive peers (whether there is a TCP connection issue or just no response as in the `nc` example).

It therefore requires an intermediary or a bogus server that doesn't respond to a protocol header.

**Comment by andrewvc** [comment] 2016-11-01 23:34
@michaelklishin confirmed this with @jordansissel . The fix is in this PR: https://github.com/ruby-amqp/march_hare/pull/108

Thanks for pointing us to the right place!

**Comment by michaelklishin** [comment] 2016-11-01 23:44
@andrewvc @jordansissel thank you for finding a way to reproduce with netcat. If there is a way for you to verify end-to-end with March Hare master, I'd be happy to do a March Hare release tomorrow morning (European time).

**Comment by michaelklishin** [comment] 2016-11-02 08:40
March Hare [2.20.0 is up](https://rubygems.org/gems/march_hare).

**Comment by digitalkaoz** [comment] 2016-11-02 08:57
@michaelklishin thanks ill test it now

**Comment by digitalkaoz** [comment] 2016-11-02 13:27
@michaelklishin @andrewvc @jordansissel  i can confirm 2.20.0 of march_hare fixed the reconnection issues. thanks for all your efforts!

**Comment by andrewvc** [comment] 2016-11-02 13:48
@digitalkaoz fantastic!

**Closed by andrewvc** 2016-11-02 13:48 UTC

**Comment by Jakauppila** [comment] 2016-11-03 19:47
Should these changes be ported over to logstash-output-rabbitmq as well?

**Comment by digitalkaoz** [comment] 2016-11-03 20:42
I think it is, because the mixin (used by Input and output) loads
march_hare the output gets this fix to. Or am i wrong?

Jared Kauppila <notifications@github.com> schrieb am Do., 3. Nov. 2016,
20:47:
